import { taskStatusFilters } from '../domain/constants'
import { useAccounts } from '../composables/useAccounts'
import { useAppShell } from '../composables/useAppShell'
import { useFailureLogs } from '../composables/useFailureLogs'
import { useSubmitter } from '../composables/useSubmitter'
import { useStaticAssets } from '../composables/useStaticAssets'
import { useServer } from '../composables/useServer'
import { useTaskFlow } from '../composables/useTaskFlow'
import { useTasks } from '../composables/useTasks'
import { reactive } from 'vue'
import { useAppServices } from './useAppServices'

export function useMonitorApp() {
  const {
    tasksApi,
    taskFlowApi,
    publisherApi,
    staticAssetsApi,
    failureLogsApi,
    distributorApi,
    operatorDiagnosticsApi,
    speakerSegmentsApi,
    ffmpegerApi,
    airouterApi,
    accountsApi,
    serverApi,
    agentApi,
    submitterApi,
    PLATFORM_ICON_URLS,
    ACCOUNT_PLATFORMS,
    accountPlatforms,
    platformIconUrls,
    brokenImageUrls,
    cacheImageUrl,
    revokeCachedUrls,
  } = useAppServices()

  const {
    rows: failureLogRows,
    loading: failureLogLoading,
    error: failureLogError,
    actionError: failureLogActionError,
    actionBusy: failureLogActionBusy,
    loadedAt: failureLogLoadedAt,
    stageFilter: failureLogStageFilter,
    typeFilter: failureLogTypeFilter,
    timeFilter: failureLogTimeFilter,
    platformFilter: failureLogPlatformFilter,
    stageOptions: failureLogStageOptions,
    typeOptions: failureLogTypeOptions,
    platformOptions: failureLogPlatformOptions,
    filteredRows: filteredFailureLogRows,
    selectedIds: failureLogSelectedIds,
    selectedSet: failureLogSelectedSet,
    allSelected: failureLogAllSelected,
    actualPublishedSelectedRows: failureLogActualPublishedSelectedRows,
    retryUploadSelectedRows: failureLogRetryUploadSelectedRows,
    abandonUploadSelectedRows: failureLogAbandonUploadSelectedRows,
    deferSelectedRows: failureLogDeferSelectedRows,
    loadFailureLogs,
    markSelectedActualPublished: markSelectedFailureLogActualPublished,
    retrySelectedUploads: retrySelectedFailureLogUploads,
    abandonSelectedUploads: abandonSelectedFailureLogUploads,
    deferSelectedTasks: deferSelectedFailureLogTasks,
    toggleRow: toggleFailureLogRow,
    toggleAll: toggleFailureLogAll,
    clearSelection: clearFailureLogSelection,
    resetFilters: resetFailureLogFilters,
  } = useFailureLogs(failureLogsApi, distributorApi)

  const {
    tasks,
    serviceHeartbeats,
    loading,
    error,
    taskStatusFilter,
    taskTypeFilter,
    taskStageFilter,
    taskIdFilter,
    taskSort,
    taskPage,
    taskTotalCount,
    taskActionsExpanded,
    openFailureKey,
    progressByTaskId,
    taskDetailsExpanded,
    taskProgressLoading,
    taskProgressError,
    taskTypeFilters,
    taskStageFilters,
    filteredTasks,
    hasTaskFilter,
    pagedTasks,
    taskPageCount,
    loadTasks,
    loadServiceHeartbeats,
    toggleTaskDetails,
    setTaskProgressPollingActive,
    loadTaskTypes,
    markTaskReady,
    isTaskReadyBusy,
    stopTask,
    canStopTask,
    isTaskStopBusy,
    restartTask,
    isTaskRestartBusy,
    deleteTask,
    isTaskDeleteBusy,
    stageName,
    failureDetails,
    failureKey,
    displayTitle,
    taskSourceUrl,
    taskThumbnailUrl,
    taskCachedThumbnailUrl,
    markImageBroken,
    sourceDurationSeconds,
    taskTypeText,
    minioStorageText,
    setTaskTypeFilter,
    setTaskStatusFilter,
    setTaskStageFilter,
    setTaskIdFilter,
    applyTaskIdFilter,
    setTaskSort,
    setTaskPage,
    copyTaskId,
    onlineDeviceText,
    serviceOnline,
    onlineDeviceTitle,
    toggleTaskActions,
    taskActionsOpen,
    nodeTitle,
    nodeProgress,
  } = useTasks(tasksApi, cacheImageUrl, brokenImageUrls, distributorApi)

  const {
    bilibiliQrCode,
    bilibiliQrMessage,
    xiaohongshuQrCode,
    xiaohongshuQrMessage,
    accountKeyGroups,
    backupperDiskStatus,
    backupperDiskStatusText,
    uploadBackfillOpen,
    uploadBackfillContext,
    uploadBackfillRows,
    uploadBackfillLoading,
    uploadBackfillBusy,
    uploadBackfillSelectedIds,
    uploadBackfillSelectedSet,
    uploadBackfillAllSelected,
    uploadBackfillError,
    uploaderPhoneMatrix,
    uploaderPhoneLoading,
    uploaderPhoneSavingKey,
    uploaderPhoneAgentBusyKey,
    uploaderPhoneError,
    standaloneAccounts,
    standaloneAccountLoading,
    standaloneAccountBusyKey,
    startAccountPolling,
    clearAccountPolling,
    togglePlatformEnabled,
    savePlatformCooldown,
    savePlatformQuietTime,
    savePlatformDownloaderMaxStagedCount,
    savePlatformNextUploadAllowedAt,
    savePlatformKey,
    savePlatformAccountProfile,
    uploadPlatformAccountAvatar,
    openUploadBackfill,
    closeUploadBackfill,
    loadUploadBackfillCandidates,
    toggleUploadBackfillRow,
    toggleUploadBackfillAll,
    registerSelectedUploadBackfill,
    saveUploaderPhoneAccount,
    runUploaderPhoneAccountScript,
    updateYoutubeDownloaderCookies,
    runStandaloneAccount,
    accountDisplay,
    accountAvatarUrl,
    accountAvatarInitial,
    accountCountText,
    nextSendText,
    platformBusyKey,
    platformBusyAction,
    platformErrorText,
    warmPlatformIcons,
    qrImageUrl,
  } = useAccounts(accountsApi, agentApi, ACCOUNT_PLATFORMS, PLATFORM_ICON_URLS)

  const {
    backupperDiskStatus: serverBackupperDiskStatus,
    backupperDiskStatusText: serverBackupperDiskStatusText,
    loading: serverLoading,
    error: serverError,
    actionBusy: serverActionBusy,
    actionMessage: serverActionMessage,
    uploadIncompleteReport: serverUploadIncompleteReport,
    uploadIncompleteReportError: serverUploadIncompleteReportError,
    loadServerStatus,
    refreshServerStatus,
    runMinioCleanup: runServerMinioCleanup,
    clearBuildCache: clearServerBuildCache,
    clearMysqlBinlog: clearServerMysqlBinlog,
    clearDiagnostics: clearServerDiagnostics,
    generateUploadIncompleteReport: generateServerUploadIncompleteReport,
  } = useServer(serverApi)

  const {
    selectedTaskFlow,
    selectedTaskProgress,
    selectedStageKey,
    flowPageOpen,
    flowLoading,
    flowError,
    speechEditDraft,
    speechEditSaving,
    speechEditError,
    uploaderDiagnostics,
    uploaderDiagnosticsLoading,
    uploaderDiagnosticsError,
    whisperWordTimestamps,
    whisperProcessing,
    selectedStage,
    flowTabs,
    openTaskFlow,
    selectTaskFlowStage,
    loadTaskFlow,
    closeTaskFlow,
    clearFlowPolling,
    setFlowPollingActive,
    refreshTaskFlow,
    loadSelectedUploaderDiagnostics,
    submitNarrationSegments,
    uploadNarrationImage,
    flowTaskTitle,
    flowSourceUrl,
    flowCoverUrl,
    flowDurationSeconds,
    tableCellText,
    tableCellSummary,
    speechRows,
    uploadSubmissionRows,
    publisherResultRows,
    stageTableRows,
    uploadPlatformName,
    speechColumns,
    showSpeechColumn,
    speechMoreRows,
    canEditSpeechDstText,
    isEditingSpeechDstText,
    beginSpeechEdit,
    cancelSpeechEdit,
    saveSpeechDstText,
    speechAudioAsset,
    stageMedia,
    demucsAudioMedia,
  } = useTaskFlow(taskFlowApi, publisherApi, brokenImageUrls)

  const {
    submitterVideos,
    submitterLoading,
    submitterError,
    submitterMessage,
    submitterInput,
    submitterBusy,
    submitterTypeFilter,
    submitterUploader,
    submitterVideoName,
    submitterDurationFilter,
    submitterPublishedFilter,
    submitterManualSubtitleFilter,
    submitterBilibiliFilter,
    submitterUploadFilter,
    submitterSort,
    submitterAuthors,
    submitterFocusedBatch,
    submitterJsonTitle,
    submitterJsonPayload,
    submitterThumbUrls,
    submitterSubmittingId,
    submitterRejectingId,
    submitterBatchSubmitting,
    submitterSelectedIds,
    submitterSelectedCount,
    submitterPageSelectableIds,
    submitterPageAllSelected,
    submitterPage,
    submitterAuthorTypeRows,
    submitterTaskTypes,
    submitterAuthorTypeSaving,
    submitterAuthorDeleting,
    submitterAuthorTypeError,
    submitterFilteredVideos,
    submitterFilteredTotal,
    submitterPageCount,
    submitterStatusCounts,
    submitterAuthorTypeFilters,
    submitterAuthorOptions,
    loadSubmitterVideos,
    applySubmitterFilters,
    loadSubmitterAuthors,
    resetSubmitterFilters,
    clearSubmitterBatchFocus,
    submitVideoToYoubi,
    submitSelectedVideosToYoubi,
    setSubmitterRowSelected,
    toggleSubmitterPageSelection,
    selectAllSubmitterFilteredVideos,
    clearSubmitterSelection,
    rejectSubmitterVideo,
    withdrawSubmitterVideo,
    submitterSubmissionStatus,
    autosaveSubmitterAuthorType,
    deleteSubmitterAuthor,
    setSubmitterPage,
    submitSubmitterInput,
    clearSubmitterPolling,
    resumeSubmitterPolling,
    submitterFieldValue,
    submitterVideoHref,
    submitterVideoTitle,
    submitterVideoThumb,
    submitterCachedThumb,
    closeSubmitterJson,
  } = useSubmitter(submitterApi, cacheImageUrl)

  const {
    assetRows,
    assetTotal,
    assetTypeCounts,
    assetLoading,
    assetError,
    assetMessage,
    assetTypeFilter,
    assetScopeFilter,
    assetTaskIdFilter,
    assetKeywordFilter,
    assetPage,
    assetPageCount,
    assetTypeSummary,
    selectedAsset,
    selectedAssetLoading,
    selectedAssetError,
    uploadAssetType,
    uploadAssetTaskId,
    uploadAssetRemark,
    uploadingAsset,
    textAssetTaskId,
    textAssetRemark,
    textAssetContent,
    creatingTextAsset,
    loadStaticAssets,
    applyStaticAssetFilters,
    resetStaticAssetFilters,
    setStaticAssetPage,
    openStaticAsset,
    closeStaticAsset,
    uploadStaticAsset,
    createStaticTextAsset,
    assetTypeLabel,
    assetContentKind,
  } = useStaticAssets(staticAssetsApi)

  const { activePage, openPage } = useAppShell({
    flowPageOpen,
    closeTaskFlow,
    loadSubmitterAuthors,
    loadSubmitterVideos,
    warmPlatformIcons,
    startAccountPolling,
    loadTasks,
    loadServiceHeartbeats,
    loadTaskTypes,
    loadFailureLogs,
    loadStaticAssets,
    loadServerStatus,
    clearAccountPolling,
    clearFlowPolling,
    clearSubmitterPolling,
    resumeSubmitterPolling,
    setTaskProgressPollingActive,
    setFlowPollingActive,
    submitterThumbUrls,
    revokeCachedUrls,
  })

  function logAudioEvent(eventName, asset, event) {
    const audio = event?.target
    const error = audio?.error
    const payload = {
      name: asset?.name || '',
      url: asset?.url || '',
      networkState: audio?.networkState,
      readyState: audio?.readyState,
      currentTime: audio?.currentTime,
      duration: audio?.duration,
      errorCode: error?.code,
      errorMessage: error ? audioErrorMessage(error.code) : '',
    }
    const logger = eventName === 'error' ? console.error : console.info
    logger('[monitor-audio]', eventName, payload)
  }

  function audioErrorMessage(code) {
    switch (code) {
      case 1:
        return 'MEDIA_ERR_ABORTED'
      case 2:
        return 'MEDIA_ERR_NETWORK'
      case 3:
        return 'MEDIA_ERR_DECODE'
      case 4:
        return 'MEDIA_ERR_SRC_NOT_SUPPORTED'
      default:
        return code ? `MEDIA_ERR_${code}` : ''
    }
  }


  return reactive({
    taskStatusFilters,
    ACCOUNT_PLATFORMS,
    PLATFORM_ICON_URLS,
    accountPlatforms,
    platformIconUrls,
    operatorDiagnosticsApi,
    speakerSegmentsApi,
    ffmpegerApi,
    airouterApi,
    logAudioEvent,
    failureLogRows,
    failureLogLoading,
    failureLogError,
    failureLogActionError,
    failureLogActionBusy,
    failureLogLoadedAt,
    failureLogStageFilter,
    failureLogTypeFilter,
    failureLogTimeFilter,
    failureLogPlatformFilter,
    failureLogStageOptions,
    failureLogTypeOptions,
    failureLogPlatformOptions,
    filteredFailureLogRows,
    failureLogSelectedIds,
    failureLogSelectedSet,
    failureLogAllSelected,
    failureLogActualPublishedSelectedRows,
    failureLogRetryUploadSelectedRows,
    failureLogAbandonUploadSelectedRows,
    failureLogDeferSelectedRows,
    loadFailureLogs,
    markSelectedFailureLogActualPublished,
    retrySelectedFailureLogUploads,
    abandonSelectedFailureLogUploads,
    deferSelectedFailureLogTasks,
    toggleFailureLogRow,
    toggleFailureLogAll,
    clearFailureLogSelection,
    resetFailureLogFilters,
    tasks,
    serviceHeartbeats,
    loading,
    error,
    taskStatusFilter,
    taskTypeFilter,
    taskStageFilter,
    taskIdFilter,
    taskSort,
    taskPage,
    taskTotalCount,
    taskActionsExpanded,
    openFailureKey,
    progressByTaskId,
    taskDetailsExpanded,
    taskProgressLoading,
    taskProgressError,
    taskTypeFilters,
    taskStageFilters,
    filteredTasks,
    hasTaskFilter,
    pagedTasks,
    taskPageCount,
    loadTasks,
    loadServiceHeartbeats,
    toggleTaskDetails,
    setTaskProgressPollingActive,
    loadTaskTypes,
    markTaskReady,
    isTaskReadyBusy,
    stopTask,
    canStopTask,
    isTaskStopBusy,
    restartTask,
    isTaskRestartBusy,
    deleteTask,
    isTaskDeleteBusy,
    stageName,
    failureDetails,
    failureKey,
    displayTitle,
    taskSourceUrl,
    taskThumbnailUrl,
    taskCachedThumbnailUrl,
    markImageBroken,
    sourceDurationSeconds,
    taskTypeText,
    minioStorageText,
    setTaskTypeFilter,
    setTaskStatusFilter,
    setTaskStageFilter,
    setTaskIdFilter,
    applyTaskIdFilter,
    setTaskSort,
    setTaskPage,
    copyTaskId,
    onlineDeviceText,
    serviceOnline,
    onlineDeviceTitle,
    toggleTaskActions,
    taskActionsOpen,
    nodeTitle,
    nodeProgress,
    bilibiliQrCode,
    bilibiliQrMessage,
    xiaohongshuQrCode,
    xiaohongshuQrMessage,
    accountKeyGroups,
    backupperDiskStatus,
    backupperDiskStatusText,
    serverBackupperDiskStatus,
    serverBackupperDiskStatusText,
    serverLoading,
    serverError,
    serverActionBusy,
    serverActionMessage,
    serverUploadIncompleteReport,
    serverUploadIncompleteReportError,
    loadServerStatus,
    refreshServerStatus,
    runServerMinioCleanup,
    clearServerBuildCache,
    clearServerMysqlBinlog,
    clearServerDiagnostics,
    generateServerUploadIncompleteReport,
    uploadBackfillOpen,
    uploadBackfillContext,
    uploadBackfillRows,
    uploadBackfillLoading,
    uploadBackfillBusy,
    uploadBackfillSelectedIds,
    uploadBackfillSelectedSet,
    uploadBackfillAllSelected,
    uploadBackfillError,
    uploaderPhoneMatrix,
    uploaderPhoneLoading,
    uploaderPhoneSavingKey,
    uploaderPhoneAgentBusyKey,
    uploaderPhoneError,
    standaloneAccounts,
    standaloneAccountLoading,
    standaloneAccountBusyKey,
    startAccountPolling,
    clearAccountPolling,
    togglePlatformEnabled,
    savePlatformCooldown,
    savePlatformQuietTime,
    savePlatformDownloaderMaxStagedCount,
    savePlatformNextUploadAllowedAt,
    savePlatformKey,
    savePlatformAccountProfile,
    uploadPlatformAccountAvatar,
    openUploadBackfill,
    closeUploadBackfill,
    loadUploadBackfillCandidates,
    toggleUploadBackfillRow,
    toggleUploadBackfillAll,
    registerSelectedUploadBackfill,
    saveUploaderPhoneAccount,
    runUploaderPhoneAccountScript,
    updateYoutubeDownloaderCookies,
    runStandaloneAccount,
    accountDisplay,
    accountAvatarUrl,
    accountAvatarInitial,
    accountCountText,
    nextSendText,
    platformBusyKey,
    platformBusyAction,
    platformErrorText,
    warmPlatformIcons,
    qrImageUrl,
    selectedTaskFlow,
    selectedTaskProgress,
    selectedStageKey,
    flowPageOpen,
    flowLoading,
    flowError,
    speechEditDraft,
    speechEditSaving,
    speechEditError,
    uploaderDiagnostics,
    uploaderDiagnosticsLoading,
    uploaderDiagnosticsError,
    whisperWordTimestamps,
    whisperProcessing,
    selectedStage,
    flowTabs,
    openTaskFlow,
    selectTaskFlowStage,
    loadTaskFlow,
    closeTaskFlow,
    clearFlowPolling,
    setFlowPollingActive,
    refreshTaskFlow,
    loadSelectedUploaderDiagnostics,
    submitNarrationSegments,
    uploadNarrationImage,
    flowTaskTitle,
    flowSourceUrl,
    flowCoverUrl,
    flowDurationSeconds,
    tableCellText,
    tableCellSummary,
    speechRows,
    uploadSubmissionRows,
    publisherResultRows,
    stageTableRows,
    uploadPlatformName,
    speechColumns,
    showSpeechColumn,
    speechMoreRows,
    canEditSpeechDstText,
    isEditingSpeechDstText,
    beginSpeechEdit,
    cancelSpeechEdit,
    saveSpeechDstText,
    speechAudioAsset,
    stageMedia,
    demucsAudioMedia,
    submitterVideos,
    submitterLoading,
    submitterError,
    submitterMessage,
    submitterInput,
    submitterBusy,
    submitterTypeFilter,
    submitterUploader,
    submitterVideoName,
    submitterDurationFilter,
    submitterPublishedFilter,
    submitterManualSubtitleFilter,
    submitterBilibiliFilter,
    submitterUploadFilter,
    submitterSort,
    submitterAuthors,
    submitterFocusedBatch,
    submitterJsonTitle,
    submitterJsonPayload,
    submitterThumbUrls,
    submitterSubmittingId,
    submitterRejectingId,
    submitterBatchSubmitting,
    submitterSelectedIds,
    submitterSelectedCount,
    submitterPageSelectableIds,
    submitterPageAllSelected,
    submitterPage,
    submitterAuthorTypeRows,
    submitterTaskTypes,
    submitterAuthorTypeSaving,
    submitterAuthorDeleting,
    submitterAuthorTypeError,
    submitterFilteredVideos,
    submitterFilteredTotal,
    submitterPageCount,
    submitterStatusCounts,
    submitterAuthorTypeFilters,
    submitterAuthorOptions,
    loadSubmitterVideos,
    applySubmitterFilters,
    loadSubmitterAuthors,
    resetSubmitterFilters,
    clearSubmitterBatchFocus,
    submitVideoToYoubi,
    submitSelectedVideosToYoubi,
    setSubmitterRowSelected,
    toggleSubmitterPageSelection,
    selectAllSubmitterFilteredVideos,
    clearSubmitterSelection,
    rejectSubmitterVideo,
    withdrawSubmitterVideo,
    submitterSubmissionStatus,
    autosaveSubmitterAuthorType,
    deleteSubmitterAuthor,
    setSubmitterPage,
    submitSubmitterInput,
    clearSubmitterPolling,
    resumeSubmitterPolling,
    submitterFieldValue,
    submitterVideoHref,
    submitterVideoTitle,
    submitterVideoThumb,
    submitterCachedThumb,
    closeSubmitterJson,
    assetRows,
    assetTotal,
    assetTypeCounts,
    assetLoading,
    assetError,
    assetMessage,
    assetTypeFilter,
    assetScopeFilter,
    assetTaskIdFilter,
    assetKeywordFilter,
    assetPage,
    assetPageCount,
    assetTypeSummary,
    selectedAsset,
    selectedAssetLoading,
    selectedAssetError,
    uploadAssetType,
    uploadAssetTaskId,
    uploadAssetRemark,
    uploadingAsset,
    textAssetTaskId,
    textAssetRemark,
    textAssetContent,
    creatingTextAsset,
    loadStaticAssets,
    applyStaticAssetFilters,
    resetStaticAssetFilters,
    setStaticAssetPage,
    openStaticAsset,
    closeStaticAsset,
    uploadStaticAsset,
    createStaticTextAsset,
    assetTypeLabel,
    assetContentKind,
    activePage,
    openPage,
  })
}
